name: ros2_env
channels:
  - pytorch
  - paddle
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
  - robostack-staging
  - conda-forge
dependencies:
  - _libavif_api=1.0.4
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.5
  - aiosignal=1.2.0
  - anyio=4.6.2
  - aom=3.9.1
  - argcomplete=1.12.0
  - assimp=5.3.1
  - astor=0.8.1
  - attrs=24.2.0
  - blas=1.0
  - blosc=1.21.5
  - boost=1.82.0
  - bottleneck=1.3.7
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bullet=3.25
  - bullet-cpp=3.25
  - bzip2=1.0.8
  - c-blosc2=2.14.4
  - c-compiler=1.8.0
  - ca-certificates=2024.9.24
  - cairo=1.18.0
  - catkin_pkg=1.0.0
  - catkin_tools=0.8.2
  - certifi=2024.8.30
  - cffi=1.17.1
  - charls=2.4.2
  - charset-normalizer=3.3.2
  - clangdev=5.0.0
  - cmake=3.26.4
  - colcon-cmake=0.2.28
  - colcon-common-extensions=0.3.0
  - colcon-core=0.18.2
  - colcon-defaults=0.2.8
  - colcon-devtools=0.3.0
  - colcon-library-path=0.2.1
  - colcon-metadata=0.2.5
  - colcon-notification=0.3.0
  - colcon-output=0.2.13
  - colcon-package-information=0.4.0
  - colcon-package-selection=0.2.10
  - colcon-parallel-executor=0.3.0
  - colcon-pkg-config=0.1.0
  - colcon-powershell=0.4.0
  - colcon-python-setup-py=0.2.9
  - colcon-recursive-crawl=0.2.3
  - colcon-ros=0.5.0
  - colcon-test-result=0.3.8
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - compilers=1.8.0
  - console_bridge=1.0.2
  - contourpy=1.2.0
  - coverage=7.6.1
  - cppcheck=2.15.0
  - cryptography=43.0.0
  - cudatoolkit=11.7.1
  - cxx-compiler=1.8.0
  - cycler=0.11.0
  - dav1d=1.2.1
  - decorator=5.1.1
  - distlib=0.3.8
  - distro=1.9.0
  - docutils=0.18.1
  - double-conversion=3.3.0
  - eigen=3.4.0
  - empy=3.3.4
  - expat=2.5.0
  - ffmpeg=6.1.1
  - filelock=3.13.1
  - flake8=7.1.1
  - flang=5.0.0
  - flang_win-64=5.0.0
  - flann=1.9.2
  - fmt=10.2.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.51.0
  - foonathan-memory=0.7.2
  - fortran-compiler=1.8.0
  - freeglut=3.4.0
  - freeimage=3.18.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.4.0
  - geos=3.13.0
  - getopt-win32=0.1
  - giflib=5.2.2
  - gl2ps=1.4.2
  - glew=2.1.0
  - glib=2.80.2
  - glib-tools=2.80.2
  - gmock=1.14.0
  - gmpy2=2.1.2
  - graphite2=1.3.14
  - graphviz=9.0.0
  - gst-plugins-base=1.24.4
  - gstreamer=1.24.4
  - gtest=1.14.0
  - gts=0.7.6
  - h11=0.14.0
  - harfbuzz=8.5.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - httpcore=1.0.2
  - httpx=0.27.0
  - humanfriendly=10.0
  - icc_rt=2022.1.0
  - icu=73.2
  - idna=3.7
  - imagecodecs=2024.6.1
  - imageio=2.36.0
  - imath=3.1.11
  - imgaug=0.4.0
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.4.0
  - iniconfig=1.1.1
  - intel-openmp=2023.1.0
  - jasper=4.2.4
  - jinja2=3.1.4
  - jsoncpp=1.9.5
  - jxrlib=1.1
  - khronos-opencl-icd-loader=2024.05.08
  - kiwisolver=1.4.4
  - krb5=1.21.3
  - lark-parser=0.12.0
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libavif16=1.0.4
  - libblas=3.9.0
  - libboost=1.82.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=18.1.7
  - libcurl=8.9.1
  - libdeflate=1.20
  - libexpat=2.5.0
  - libffi=3.4.4
  - libflang=5.0.0
  - libgd=2.3.3
  - libgettextpo=0.22.5
  - libglib=2.80.2
  - libhwloc=2.11.1
  - libiconv=1.17
  - libignition-cmake2=2.17.2
  - libignition-math6=6.15.1
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.3
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnetcdf=4.9.2
  - libogg=1.3.5
  - libopencv=4.9.0
  - libopenvino=2024.1.0
  - libopenvino-auto-batch-plugin=2024.1.0
  - libopenvino-auto-plugin=2024.1.0
  - libopenvino-hetero-plugin=2024.1.0
  - libopenvino-intel-cpu-plugin=2024.1.0
  - libopenvino-intel-gpu-plugin=2024.1.0
  - libopenvino-ir-frontend=2024.1.0
  - libopenvino-onnx-frontend=2024.1.0
  - libopenvino-paddle-frontend=2024.1.0
  - libopenvino-pytorch-frontend=2024.1.0
  - libopenvino-tensorflow-frontend=2024.1.0
  - libopenvino-tensorflow-lite-frontend=2024.1.0
  - libopus=1.3.1
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libraw=0.21.1
  - libsqlite=3.47.0
  - libssh2=1.11.0
  - libtheora=1.1.1
  - libtiff=4.6.0
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libwebp=1.4.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxml2=2.13.1
  - libxslt=1.1.41
  - libzip=1.10.1
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvm-meta=5.0.0
  - loguru=0.7.2
  - lxml=5.2.1
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - make=4.4.1
  - markupsafe=2.1.3
  - matplotlib-base=3.9.2
  - mccabe=0.7.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - msgpack-python=1.0.3
  - msys2-conda-epoch=20160418
  - multidict=6.0.4
  - netifaces=0.11.0
  - networkx=3.3
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nlohmann_json=3.11.2
  - numexpr=2.8.4
  - numpy=1.26.4
  - opencv=4.9.0
  - openexr=3.2.2
  - openh264=2.4.1
  - openjpeg=2.5.2
  - openmp=5.0.0
  - openssl=3.3.2
  - opt_einsum=3.3.0
  - orocos-kdl=1.5.1
  - osrf_pycommon=0.2.1
  - packaging=24.1
  - paddlepaddle=3.0.0b2
  - pandas=2.2.2
  - pango=1.54.0
  - pcl=1.13.1
  - pcre=8.45
  - pcre2=10.43
  - pep517=0.12.0
  - pillow=10.3.0
  - pip=24.2
  - pixman=0.43.4
  - pkg-config=0.29.2
  - pluggy=1.0.0
  - ply=3.11
  - proj=9.3.1
  - protobuf=4.25.3
  - psutil=5.9.0
  - pthread-stubs=0.3
  - pthreads-win32=2.9.1
  - pugixml=1.14
  - py-boost=1.82.0
  - py-cpuinfo=9.0.0
  - py-opencv=4.9.0
  - pybind11=2.10.4
  - pybind11-abi=4
  - pybind11-global=2.10.4
  - pybullet=3.25
  - pycairo=1.23.0
  - pycodestyle=2.12.1
  - pycparser=2.21
  - pydocstyle=6.3.0
  - pydot=3.0.1
  - pyflakes=3.2.0
  - pygments=2.15.1
  - pyparsing=3.1.2
  - pyqt=5.15.10
  - pyqt-builder=1.15.3
  - pyqt5-sip=12.13.0
  - pyreadline3=3.4.1
  - pysocks=1.7.1
  - pytest=7.4.4
  - pytest-cov=4.1.0
  - pytest-repeat=0.9.2
  - pytest-rerunfailures=12.0
  - python=3.11.10
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytorch=2.3.0
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pywavelets=1.7.0
  - pywin32=305
  - pyyaml=6.0.2
  - qhull=2020.2
  - qt-main=5.15.8
  - qt6-main=6.7.1
  - rav1e=0.6.6
  - requests=2.32.3
  - ros-humble-action-msgs=1.2.1
  - ros-humble-action-tutorials-cpp=0.20.3
  - ros-humble-action-tutorials-interfaces=0.20.3
  - ros-humble-action-tutorials-py=0.20.3
  - ros-humble-actionlib-msgs=4.2.3
  - ros-humble-ament-cmake=1.3.8
  - ros-humble-ament-cmake-auto=1.3.8
  - ros-humble-ament-cmake-copyright=0.12.10
  - ros-humble-ament-cmake-core=1.3.8
  - ros-humble-ament-cmake-cppcheck=0.12.10
  - ros-humble-ament-cmake-cpplint=0.12.10
  - ros-humble-ament-cmake-export-definitions=1.3.8
  - ros-humble-ament-cmake-export-dependencies=1.3.8
  - ros-humble-ament-cmake-export-include-directories=1.3.8
  - ros-humble-ament-cmake-export-interfaces=1.3.8
  - ros-humble-ament-cmake-export-libraries=1.3.8
  - ros-humble-ament-cmake-export-link-flags=1.3.8
  - ros-humble-ament-cmake-export-targets=1.3.8
  - ros-humble-ament-cmake-flake8=0.12.10
  - ros-humble-ament-cmake-gen-version-h=1.3.8
  - ros-humble-ament-cmake-gmock=1.3.8
  - ros-humble-ament-cmake-gtest=1.3.8
  - ros-humble-ament-cmake-include-directories=1.3.8
  - ros-humble-ament-cmake-libraries=1.3.8
  - ros-humble-ament-cmake-lint-cmake=0.12.10
  - ros-humble-ament-cmake-pep257=0.12.10
  - ros-humble-ament-cmake-pytest=1.3.8
  - ros-humble-ament-cmake-python=1.3.8
  - ros-humble-ament-cmake-ros=0.10.0
  - ros-humble-ament-cmake-target-dependencies=1.3.8
  - ros-humble-ament-cmake-test=1.3.8
  - ros-humble-ament-cmake-uncrustify=0.12.10
  - ros-humble-ament-cmake-version=1.3.8
  - ros-humble-ament-cmake-xmllint=0.12.10
  - ros-humble-ament-copyright=0.12.10
  - ros-humble-ament-cppcheck=0.12.10
  - ros-humble-ament-cpplint=0.12.10
  - ros-humble-ament-flake8=0.12.10
  - ros-humble-ament-index-cpp=1.4.0
  - ros-humble-ament-index-python=1.4.0
  - ros-humble-ament-lint=0.12.10
  - ros-humble-ament-lint-auto=0.12.10
  - ros-humble-ament-lint-cmake=0.12.10
  - ros-humble-ament-lint-common=0.12.10
  - ros-humble-ament-package=0.14.0
  - ros-humble-ament-pep257=0.12.10
  - ros-humble-ament-uncrustify=0.12.10
  - ros-humble-ament-xmllint=0.12.10
  - ros-humble-angles=1.15.0
  - ros-humble-builtin-interfaces=1.2.1
  - ros-humble-class-loader=2.2.0
  - ros-humble-common-interfaces=4.2.3
  - ros-humble-composition=0.20.3
  - ros-humble-composition-interfaces=1.2.1
  - ros-humble-console-bridge-vendor=1.4.1
  - ros-humble-cv-bridge=3.2.1
  - ros-humble-demo-nodes-cpp=0.20.3
  - ros-humble-demo-nodes-cpp-native=0.20.3
  - ros-humble-demo-nodes-py=0.20.3
  - ros-humble-depthimage-to-laserscan=2.5.1
  - ros-humble-desktop=0.10.0
  - ros-humble-diagnostic-msgs=4.2.3
  - ros-humble-domain-coordinator=0.10.0
  - ros-humble-dummy-map-server=0.20.3
  - ros-humble-dummy-robot-bringup=0.20.3
  - ros-humble-dummy-sensors=0.20.3
  - ros-humble-eigen3-cmake-module=0.1.1
  - ros-humble-example-interfaces=0.9.3
  - ros-humble-examples-rclcpp-minimal-action-client=0.15.1
  - ros-humble-examples-rclcpp-minimal-action-server=0.15.1
  - ros-humble-examples-rclcpp-minimal-client=0.15.1
  - ros-humble-examples-rclcpp-minimal-composition=0.15.1
  - ros-humble-examples-rclcpp-minimal-publisher=0.15.1
  - ros-humble-examples-rclcpp-minimal-service=0.15.1
  - ros-humble-examples-rclcpp-minimal-subscriber=0.15.1
  - ros-humble-examples-rclcpp-minimal-timer=0.15.1
  - ros-humble-examples-rclcpp-multithreaded-executor=0.15.1
  - ros-humble-examples-rclpy-executors=0.15.1
  - ros-humble-examples-rclpy-minimal-action-client=0.15.1
  - ros-humble-examples-rclpy-minimal-action-server=0.15.1
  - ros-humble-examples-rclpy-minimal-client=0.15.1
  - ros-humble-examples-rclpy-minimal-publisher=0.15.1
  - ros-humble-examples-rclpy-minimal-service=0.15.1
  - ros-humble-examples-rclpy-minimal-subscriber=0.15.1
  - ros-humble-fastcdr=1.0.24
  - ros-humble-fastrtps=2.6.7
  - ros-humble-fastrtps-cmake-module=2.2.2
  - ros-humble-foonathan-memory-vendor=1.2.0
  - ros-humble-geometry-msgs=4.2.3
  - ros-humble-geometry2=0.25.6
  - ros-humble-gmock-vendor=1.10.9004
  - ros-humble-gtest-vendor=1.10.9004
  - ros-humble-ignition-cmake2-vendor=0.0.2
  - ros-humble-ignition-math6-vendor=0.0.2
  - ros-humble-image-geometry=3.2.1
  - ros-humble-image-tools=0.20.3
  - ros-humble-image-transport=3.1.9
  - ros-humble-interactive-markers=2.3.2
  - ros-humble-intra-process-demo=0.20.3
  - ros-humble-joy=3.3.0
  - ros-humble-kdl-parser=2.6.4
  - ros-humble-keyboard-handler=0.0.5
  - ros-humble-laser-geometry=2.4.0
  - ros-humble-launch=1.0.5
  - ros-humble-launch-ros=0.19.7
  - ros-humble-launch-testing=1.0.5
  - ros-humble-launch-testing-ament-cmake=1.0.5
  - ros-humble-launch-testing-ros=0.19.7
  - ros-humble-launch-xml=1.0.5
  - ros-humble-launch-yaml=1.0.5
  - ros-humble-libcurl-vendor=3.1.2
  - ros-humble-libstatistics-collector=1.3.1
  - ros-humble-libyaml-vendor=1.2.2
  - ros-humble-lifecycle=0.20.3
  - ros-humble-lifecycle-msgs=1.2.1
  - ros-humble-logging-demo=0.20.3
  - ros-humble-map-msgs=2.1.0
  - ros-humble-message-filters=4.3.3
  - ros-humble-nav-msgs=4.2.3
  - ros-humble-orocos-kdl-vendor=0.2.5
  - ros-humble-osrf-pycommon=2.0.2
  - ros-humble-pcl-conversions=2.4.0
  - ros-humble-pcl-msgs=1.0.0
  - ros-humble-pendulum-msgs=0.20.3
  - ros-humble-pluginlib=5.1.0
  - ros-humble-pybind11-vendor=2.4.2
  - ros-humble-python-cmake-module=0.10.0
  - ros-humble-python-qt-binding=1.1.2
  - ros-humble-qt-dotgraph=2.2.3
  - ros-humble-qt-gui=2.2.3
  - ros-humble-qt-gui-cpp=2.2.3
  - ros-humble-qt-gui-py-common=2.2.3
  - ros-humble-quality-of-service-demo-cpp=0.20.3
  - ros-humble-quality-of-service-demo-py=0.20.3
  - ros-humble-rcl=5.3.7
  - ros-humble-rcl-action=5.3.7
  - ros-humble-rcl-interfaces=1.2.1
  - ros-humble-rcl-lifecycle=5.3.7
  - ros-humble-rcl-logging-interface=2.3.1
  - ros-humble-rcl-logging-spdlog=2.3.1
  - ros-humble-rcl-yaml-param-parser=5.3.7
  - ros-humble-rclcpp=16.0.8
  - ros-humble-rclcpp-action=16.0.8
  - ros-humble-rclcpp-components=16.0.8
  - ros-humble-rclcpp-lifecycle=16.0.8
  - ros-humble-rclpy=3.3.12
  - ros-humble-rcpputils=2.4.2
  - ros-humble-rcutils=5.1.5
  - ros-humble-resource-retriever=3.1.2
  - ros-humble-rmw=6.1.1
  - ros-humble-rmw-connextdds=0.11.2
  - ros-humble-rmw-connextdds-common=0.11.2
  - ros-humble-rmw-dds-common=1.6.0
  - ros-humble-rmw-fastrtps-cpp=6.2.6
  - ros-humble-rmw-fastrtps-dynamic-cpp=6.2.6
  - ros-humble-rmw-fastrtps-shared-cpp=6.2.6
  - ros-humble-rmw-implementation=2.8.2
  - ros-humble-rmw-implementation-cmake=6.1.1
  - ros-humble-robot-state-publisher=3.0.3
  - ros-humble-ros-base=0.10.0
  - ros-humble-ros-core=0.10.0
  - ros-humble-ros-environment=3.2.2
  - ros-humble-ros-workspace=1.0.2
  - ros-humble-ros2action=0.18.9
  - ros-humble-ros2bag=0.15.9
  - ros-humble-ros2cli=0.18.9
  - ros-humble-ros2cli-common-extensions=0.1.1
  - ros-humble-ros2component=0.18.9
  - ros-humble-ros2doctor=0.18.9
  - ros-humble-ros2interface=0.18.9
  - ros-humble-ros2launch=0.19.7
  - ros-humble-ros2lifecycle=0.18.9
  - ros-humble-ros2multicast=0.18.9
  - ros-humble-ros2node=0.18.9
  - ros-humble-ros2param=0.18.9
  - ros-humble-ros2pkg=0.18.9
  - ros-humble-ros2run=0.18.9
  - ros-humble-ros2service=0.18.9
  - ros-humble-ros2topic=0.18.9
  - ros-humble-rosbag2=0.15.9
  - ros-humble-rosbag2-compression=0.15.9
  - ros-humble-rosbag2-compression-zstd=0.15.9
  - ros-humble-rosbag2-cpp=0.15.9
  - ros-humble-rosbag2-interfaces=0.15.9
  - ros-humble-rosbag2-py=0.15.9
  - ros-humble-rosbag2-storage=0.15.9
  - ros-humble-rosbag2-storage-default-plugins=0.15.9
  - ros-humble-rosbag2-transport=0.15.9
  - ros-humble-rosgraph-msgs=1.2.1
  - ros-humble-rosidl-adapter=3.1.5
  - ros-humble-rosidl-cli=3.1.5
  - ros-humble-rosidl-cmake=3.1.5
  - ros-humble-rosidl-default-generators=1.2.0
  - ros-humble-rosidl-default-runtime=1.2.0
  - ros-humble-rosidl-generator-c=3.1.5
  - ros-humble-rosidl-generator-cpp=3.1.5
  - ros-humble-rosidl-generator-py=0.14.4
  - ros-humble-rosidl-parser=3.1.5
  - ros-humble-rosidl-runtime-c=3.1.5
  - ros-humble-rosidl-runtime-cpp=3.1.5
  - ros-humble-rosidl-runtime-py=0.9.3
  - ros-humble-rosidl-typesupport-c=2.0.1
  - ros-humble-rosidl-typesupport-cpp=2.0.1
  - ros-humble-rosidl-typesupport-fastrtps-c=2.2.2
  - ros-humble-rosidl-typesupport-fastrtps-cpp=2.2.2
  - ros-humble-rosidl-typesupport-interface=3.1.5
  - ros-humble-rosidl-typesupport-introspection-c=3.1.5
  - ros-humble-rosidl-typesupport-introspection-cpp=3.1.5
  - ros-humble-rpyutils=0.2.1
  - ros-humble-rqt-action=2.0.1
  - ros-humble-rqt-bag=1.1.4
  - ros-humble-rqt-bag-plugins=1.1.4
  - ros-humble-rqt-common-plugins=1.2.0
  - ros-humble-rqt-console=2.0.2
  - ros-humble-rqt-graph=1.3.0
  - ros-humble-rqt-gui=1.1.6
  - ros-humble-rqt-gui-cpp=1.1.6
  - ros-humble-rqt-gui-py=1.1.6
  - ros-humble-rqt-image-view=1.2.0
  - ros-humble-rqt-msg=1.2.0
  - ros-humble-rqt-plot=1.1.2
  - ros-humble-rqt-publisher=1.5.0
  - ros-humble-rqt-py-common=1.1.6
  - ros-humble-rqt-py-console=1.0.2
  - ros-humble-rqt-reconfigure=1.1.2
  - ros-humble-rqt-service-caller=1.0.5
  - ros-humble-rqt-shell=1.0.2
  - ros-humble-rqt-srv=1.0.3
  - ros-humble-rqt-topic=1.5.0
  - ros-humble-rti-connext-dds-cmake-module=0.11.2
  - ros-humble-rviz-assimp-vendor=11.2.12
  - ros-humble-rviz-common=11.2.12
  - ros-humble-rviz-default-plugins=11.2.12
  - ros-humble-rviz-ogre-vendor=11.2.12
  - ros-humble-rviz-rendering=11.2.12
  - ros-humble-rviz2=11.2.12
  - ros-humble-sdl2-vendor=3.3.0
  - ros-humble-sensor-msgs=4.2.3
  - ros-humble-sensor-msgs-py=4.2.4
  - ros-humble-shape-msgs=4.2.3
  - ros-humble-shared-queues-vendor=0.15.9
  - ros-humble-spdlog-vendor=1.3.1
  - ros-humble-sqlite3-vendor=0.15.9
  - ros-humble-sros2=0.10.4
  - ros-humble-sros2-cmake=0.10.4
  - ros-humble-statistics-msgs=1.2.1
  - ros-humble-std-msgs=4.2.3
  - ros-humble-std-srvs=4.2.3
  - ros-humble-stereo-msgs=4.2.3
  - ros-humble-tango-icons-vendor=0.1.1
  - ros-humble-teleop-twist-joy=2.4.5
  - ros-humble-teleop-twist-keyboard=2.3.2
  - ros-humble-tf2=0.25.6
  - ros-humble-tf2-bullet=0.25.6
  - ros-humble-tf2-eigen=0.25.6
  - ros-humble-tf2-eigen-kdl=0.25.6
  - ros-humble-tf2-geometry-msgs=0.25.6
  - ros-humble-tf2-kdl=0.25.6
  - ros-humble-tf2-msgs=0.25.6
  - ros-humble-tf2-py=0.25.6
  - ros-humble-tf2-ros=0.25.6
  - ros-humble-tf2-ros-py=0.25.6
  - ros-humble-tf2-sensor-msgs=0.25.6
  - ros-humble-tf2-tools=0.25.6
  - ros-humble-tinyxml-vendor=0.8.3
  - ros-humble-tinyxml2-vendor=0.7.6
  - ros-humble-topic-monitor=0.20.3
  - ros-humble-tracetools=4.1.1
  - ros-humble-trajectory-msgs=4.2.3
  - ros-humble-turtlesim=1.4.2
  - ros-humble-uncrustify-vendor=2.0.2
  - ros-humble-unique-identifier-msgs=2.2.1
  - ros-humble-urdf=2.6.0
  - ros-humble-urdf-parser-plugin=2.6.0
  - ros-humble-urdfdom=3.0.2
  - ros-humble-urdfdom-headers=1.0.6
  - ros-humble-visualization-msgs=4.2.3
  - ros-humble-yaml-cpp-vendor=8.0.2
  - ros-humble-zstd-vendor=0.15.9
  - ros2-distro-mutex=0.5.0
  - rosdep=0.25.1
  - rosdistro=0.9.0
  - rospkg=1.5.1
  - scikit-image=0.24.0
  - scipy=1.14.1
  - sdl2=2.30.7
  - seaborn=0.13.2
  - setuptools=75.1.0
  - shapely=2.0.6
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - snowballstemmer=2.2.0
  - spdlog=1.12.0
  - sqlite=3.45.3
  - svt-av1=2.1.0
  - tbb=2021.13.0
  - tbb-devel=2021.13.0
  - tifffile=2024.9.20
  - tinyxml=2.6.2
  - tinyxml2=10.0.0
  - tk=8.6.14
  - toml=0.10.2
  - tomli=2.0.1
  - torchaudio=2.3.0
  - torchvision=0.18.0
  - tqdm=4.66.5
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024b
  - ucrt=10.0.20348.0
  - ultralytics=8.3.27
  - uncrustify=0.74.0
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - utfcpp=3.2.1
  - vc=14.40
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - vs2019_win-64=19.29.30154
  - vswhere=2.8.4
  - vtk=9.2.6
  - vtk-base=9.2.6
  - wheel=0.44.0
  - win32_setctime=1.1.0
  - win_inet_pton=1.1.0
  - wslink=2.2.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.17
  - xorg-libxt=1.3.0
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.4.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yarl=1.11.0
  - zfp=1.0.1
  - zipp=3.20.2
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.6
  - zziplib=0.13.69
  - pip:
      - albucore==0.0.13
      - albumentations==1.4.10
      - annotated-types==0.7.0
      - beautifulsoup4==4.12.3
      - cython==3.0.11
      - fire==0.7.0
      - fsspec==2024.10.0
      - joblib==1.4.2
      - lmdb==1.5.1
      - opencv-contrib-python==4.10.0.84
      - opencv-python-headless==4.10.0.84
      - paddleocr==2.9.1
      - pyclipper==1.3.0.post6
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - python-docx==1.1.2
      - rapidfuzz==3.10.1
      - scikit-learn==1.5.2
      - simsimd==6.0.1
      - soupsieve==2.6
      - stringzilla==3.10.7
      - sympy==1.13.1
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - pyautogui
prefix: C:\Users\marce\miniforge3\envs\ros2_env
